sudo: required
language: php
php:
  - '7.2'

services:
  - docker

before_install:
    # Optimize composer download
    - composer global require hirak/prestissimo
    # Run docker
    - docker run -p 127.0.0.1:32770:80 -p 127.0.0.1:32771:3306 -d -h pandorafms -v "$TRAVIS_BUILD_DIR:/tmp/pandorafms" pandorafms/pandorafms-base /tmp/pandorafms/tests/test.sh
    # Extract the initial database seed, so we can reset it for the testing phase
    - sleep 25
    - curl -s http://127.0.0.1:32770/pandora_console/initial_seed.sql -o $TRAVIS_BUILD_DIR/tests/console/pandora-codeception/tests/_data/initial_seed.sql


script:
  - cd tests/console/pandora-codeception && composer install
  - php vendor/bin/codecept run acceptance createUser.feature
  
